version: "3.1"
services:
        backend:
                build: ./backend
                restart: always
                volumes:
                        - ./backend:/app
                environment:
                        PORT: 8000
                networks:
                        - web_network # for web API

        frontend:
                build: ./frontend
                restart: unless-stopped
                volumes:
                        - web-root:/home/app/public
                        - ./frontend:/home/app/public
                        - /home/app/node_modules
                environment:
                        - PORT=5000
                        - HOST=0.0.0.0 # Make sirv listen on all IPs for NGINX
                depends_on:
                        - backend
                networks:
                        - web_network

        nginx:
                image: nginx:latest
                ports:
                        - 8000:80
                volumes:
                        - web-root:/var/www/html
                        - ./nginx:/etc/nginx/conf.d/
                depends_on:
                        - backend
                        - db-interface
                networks:
                        - web_network

networks:
        web_network:
            driver: bridge

volumes:
        web-root:
# https://github.com/Synalytica/fastapi-svelte-template/blob/master/docker-compose.yml